spring:
  application:
    name: HAB-card-generator

# Label background color (hex value without #, e.g., FFFF00 for yellow)
label:
  background:
    color: 9fd6e0

# CardData Excel column mappings (column names)
card:
  data:
    splitOddEven: true
    useNewLine: true
    inputDirectory: "C:/03-resources/Hoge Akkersbloei/members"
    columns:
      memberId: id
      name: 'naam'
      street: 'street '
      streetNumber: street number
